site_name: MacAdmins Community Documentation
repo_url: https://github.com/Shufflepuck/MacAdminsDoc
repo_name: 'GitHub'
copyright: Creative Commons Attribution-ShareAlike 4.0 International License
google_analytics: ['UA-68588325-4']



